### ISSUE TITLE
Auth0 requires an "audience" to be sent for the client credentials flow

### ISSUE THREAD

**Issue by jonathan-graf** [softonic/guzzle-oauth2-middleware#14]
Auth0 framework offers a client credentials flow, as it is OAuth2-compliant.  However, in addition to a `grant_type` config, it also requires an `audience` config.

Reference:
https://auth0.com/docs/flows/guides/client-credentials/call-api-client-credentials

In AddAuthorizationHeader.getOptions(), if we could add logic like this:
```
private function getOptions(): array
    {
        $options = [];
        if (!empty($this->config['scope'])) {
            $options['scope'] = $this->config['scope'];
        }
        if (!empty($this->config['audience'])) {
            $options['audience'] = $this->config['audience'];
        }
        return $options;
    }
```

**Comment by rccrdpccl** [comment]
This looks reasonable to me, although it's specific to an implementation. Could we make this beahviour generic, instead of hard-coding possible custom values?

A possible solution might be specifying all token options below a config attribute (maintaining scope also in root level, for backward compatibility). Something like:
`$config = [
   'scope' => ...,
   'token_options' => [
      'audience' => ...
   ]
]`

However I am open to other solutions if you have anything to suggest.

Sorry for the delays that this might take due to holidays season, please feel free to ping me if this does not move forward.

**Comment by jonathan-graf** [comment]
Thank you kindly.  Merry Christmas and Happy Holidays to you.

I think the solution to put custom config attributes within `$config` makes perfect sense.  I also agree this should not be specific to an implementation.

I would say the `$token_options[]` above is a good solution, or consider just dumping everything in `$config[]` into `$options[]` (because I'm not entirely sure what the difference would be regarding items in the `config` array vs. items in the potential `token_options` array).

I cannot submit a pull request because I am not a collaborator.

**Comment by rccrdpccl** [comment]
The idea was to have `$config['token_options']`, so that we can avoid passing some needed config parameters as token options (`grant_type` for example).

If you like the proposal please feel free to submit a pull request: you can fork the repo and submit the PR from your own repo against our master branch.

Sorry for the delay, hopefully this process might get faster as holidays will be over soon.
